### ISSUE TITLE
Whittier Interchange

### ISSUE THREAD

**Issue by tyrope** [SgtMoloch/InterchangeUnchained#5]
From the readme:
> Whittier Interchange is unaffected because it only has 2 avaiable tracks.

There's a third track, albeit really short, on the north end of the yard. The amount of times I've put an empty coal car here and be disappointed it still being empty by morning...

**Comment by SgtMoloch** [comment]
I will not be adding the 3rd track in Whittier as an interchange track as part of this mod. Potentially as another mod, but I make no promises or guarantees.
